### ISSUE TITLE
top and bottom rail clearance is way too small

### ISSUE THREAD

**Issue by av500** [loglow/uBraids_SE#1]
Eurorack has about 9mm top and bottom clearance, leaving ~110mm for the PCB. you have only 6.5mm on the top and ~7mm on the bottom which makes the module not fit with most Eurorack rails.

**Comment by loglow** [comment]
Hi av500, thanks for submitting the feedback.

We're aware of this, and in fact, I've already done a bunch of work to correct it. We tested the module with a number of different rails, but clearly not enough! Further research showed us that while some rails do have > 115 mm clearance, there are also many with 111-112 mm clearance.

The main board has already been shaved down from 115 mm to 110.5 mm and re-centered relative to the front panel. I'll be updating the repo here with the new files very shortly. I may still try to eliminate another 0.5 mm just for good measure.

Thanks again,
Dan

**Comment by loglow** [comment]
Updated revised files to address the rail clearance issue.

**Comment by loglow** [comment]
Updated again with a 110 mm version.
